title: Portfolio | Home
author: Remilekun Elijah
email: Remilekunelijah21997@dgmail.com
description: Blog Website| portfolio website | Team Collaboration | Hire | Business Website

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
