title: My Portfolio
author: Remilekun-Elijah
email: Remilekunelijah21997@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Portfolio sites builder | business website builder | team collaboration | code tutor | web developer | programmer | best portfpolio builders
  # social links
twitter_username: github.com/Remilekun-Elijah
github_username:  twitter.com/RemilekunElijah

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
